### ISSUE TITLE
Use FLAN variant of T5

### ISSUE THREAD

**Issue by delip** [lucidrains/audiolm-pytorch#15]
Not sure where to leave suggestions, but I would consider replacing T5 with T5-FLAN (also available via HuggingFace) for a better bang for the buck.

**Comment by zqevans** [comment]
I'm working on a separate text-to-audio model, and also curious about what the best pretrained text encoder is to use. I've been using the original T5-base checkpoint just because that's what Imagen used (as well as the larger T5 models). It's working well, I haven't had a chance to try out different encoders.

**Comment by lucidrains** [comment]
@delip Hi Delip, it is actually fully customizable which T5 to use by simply setting the `t5_name` https://github.com/lucidrains/audiolm-pytorch/blob/main/audiolm_pytorch/audiolm_pytorch.py#L319

in your case, you would set it to `"google/flan-t5-large"`

happy experimenting
